-- =============================================================================
-- Vision OCR - application schema for Microsoft SQL Server (2016 SP1 or later / Azure SQL)
--
-- SAFE FOR AN EXISTING DATABASE:
--   * every object lives in the dedicated schema "ocr" - nothing in dbo or other schemas is touched
--   * additive only: missing tables, columns and indexes are created; nothing is ever dropped
--     (the only CREATE OR ALTER is the view ocr.v_doc_field_final, owned by this job)
--   * large tables are created with PAGE compression (SQL Server 2016 SP1+, all editions); for tables
--     created by an earlier version see ops/operations.sql (REBUILD WITH DATA_COMPRESSION = PAGE)
-- The job can run it at startup (db.init=true) or a DBA runs it once and sets db.init=false.
--
--   doc_job                 one row per input file = current state (the "work queue")
--   doc_azure_result        every successful Azure call: full JSON + simplified fields (history kept)
--   doc_field               extracted fields, one row per field (generic for every doc type)
--   doc_field_correction    human corrections (never overwrite model output)
--   doc_status_history      every status transition (audit trail)
--   doc_error               every failure, with stage / attempt / retryable flag
--   doc_reprocess_request   operator requests to re-run documents from a given stage
--   v_doc_field_final       what downstream systems read: correction wins over extraction
--   v_doc_<doctype>         generated by the job at runtime in schema ocr (one column per field)
--
-- JSON columns are NVARCHAR(MAX) with an ISJSON check - query them with JSON_VALUE / OPENJSON.
-- =============================================================================

IF SCHEMA_ID(N'ocr') IS NULL EXEC(N'CREATE SCHEMA ocr');

-- -----------------------------------------------------------------------------
-- doc_job
-- -----------------------------------------------------------------------------
IF OBJECT_ID(N'ocr.doc_job', N'U') IS NULL
CREATE TABLE ocr.doc_job (
    id                  BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT pk_doc_job PRIMARY KEY,
    file_path           NVARCHAR(1024) NOT NULL,
    file_name           NVARCHAR(255)  NOT NULL,
    file_hash           VARCHAR(64)    NOT NULL CONSTRAINT uq_doc_job_hash UNIQUE,
    file_size           BIGINT         NULL,
    status              VARCHAR(20)    NOT NULL,
    doc_type            VARCHAR(50)    NULL,
    classifier_label    NVARCHAR(100)  NULL,
    classify_confidence FLOAT          NULL,
    pages               VARCHAR(100)   NULL,
    model_id            NVARCHAR(200)  NULL,
    doc_confidence      FLOAT          NULL,
    review_reasons      NVARCHAR(2000) NULL,
    extracted_json      NVARCHAR(MAX)  NULL,
    failed_stage        VARCHAR(20)    NULL,
    retry_count         INT            NOT NULL CONSTRAINT df_doc_job_retry_count DEFAULT 0,
    next_retry_at       DATETIME2      NULL,
    last_error          NVARCHAR(2000) NULL,
    created_at          DATETIME2      NOT NULL CONSTRAINT df_doc_job_created_at DEFAULT SYSDATETIME(),
    updated_at          DATETIME2      NOT NULL CONSTRAINT df_doc_job_updated_at DEFAULT SYSDATETIME(),
    CONSTRAINT ck_doc_job_status CHECK (status IN
        ('NEW', 'CLASSIFIED', 'EXTRACTED', 'COMPLETED', 'REVIEW', 'ERROR', 'FAILED')),
    CONSTRAINT ck_doc_job_json CHECK (extracted_json IS NULL OR ISJSON(extracted_json) = 1)
);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_job_status' AND object_id = OBJECT_ID(N'ocr.doc_job'))
    CREATE INDEX ix_doc_job_status ON ocr.doc_job (status, id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_job_retry' AND object_id = OBJECT_ID(N'ocr.doc_job'))
    CREATE INDEX ix_doc_job_retry ON ocr.doc_job (status, next_retry_at);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_job_type' AND object_id = OBJECT_ID(N'ocr.doc_job'))
    CREATE INDEX ix_doc_job_type ON ocr.doc_job (doc_type, status, created_at);

-- -----------------------------------------------------------------------------
-- doc_azure_result
-- -----------------------------------------------------------------------------
IF OBJECT_ID(N'ocr.doc_azure_result', N'U') IS NULL
CREATE TABLE ocr.doc_azure_result (
    id              BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT pk_doc_azure_result PRIMARY KEY,
    doc_id          BIGINT        NOT NULL CONSTRAINT fk_doc_azure_result_job REFERENCES ocr.doc_job (id),
    operation       VARCHAR(20)   NOT NULL,
    model_id        NVARCHAR(200) NOT NULL,
    api_version     VARCHAR(20)   NULL,
    doc_confidence  FLOAT         NULL,
    result_json     NVARCHAR(MAX) NULL,
    fields_json     NVARCHAR(MAX) NULL,
    duration_ms     BIGINT        NULL,
    is_current      BIT           NOT NULL CONSTRAINT df_doc_azure_result_current DEFAULT 1,
    created_at      DATETIME2     NOT NULL CONSTRAINT df_doc_azure_result_created DEFAULT SYSDATETIME(),
    result_json_gz  VARBINARY(MAX) NULL,                 -- full Azure response, COMPRESS()ed (GZIP)
    CONSTRAINT ck_doc_azure_result_op CHECK (operation IN ('CLASSIFY', 'EXTRACT'))
) WITH (DATA_COMPRESSION = PAGE);

-- added in a later version: compressed copy of the Azure response (result_json is kept for older rows)
IF COL_LENGTH(N'ocr.doc_azure_result', N'result_json_gz') IS NULL
    ALTER TABLE ocr.doc_azure_result ADD result_json_gz VARBINARY(MAX) NULL;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_azure_result_doc' AND object_id = OBJECT_ID(N'ocr.doc_azure_result'))
    CREATE INDEX ix_doc_azure_result_doc ON ocr.doc_azure_result (doc_id, operation, is_current);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_azure_result_at' AND object_id = OBJECT_ID(N'ocr.doc_azure_result'))
    CREATE INDEX ix_doc_azure_result_at ON ocr.doc_azure_result (created_at);

-- -----------------------------------------------------------------------------
-- doc_field  (value_key = first 400 chars of the value, indexed for lookups by value)
-- -----------------------------------------------------------------------------
IF OBJECT_ID(N'ocr.doc_field', N'U') IS NULL
CREATE TABLE ocr.doc_field (
    id            BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT pk_doc_field PRIMARY KEY,
    doc_id        BIGINT         NOT NULL CONSTRAINT fk_doc_field_job REFERENCES ocr.doc_job (id),
    result_id     BIGINT         NULL CONSTRAINT fk_doc_field_result REFERENCES ocr.doc_azure_result (id),
    doc_type      VARCHAR(50)    NOT NULL,
    field_name    NVARCHAR(200)  NOT NULL,
    azure_field   NVARCHAR(200)  NULL,
    field_value   NVARCHAR(4000) NULL,
    raw_value     NVARCHAR(4000) NULL,
    confidence    FLOAT          NULL,
    field_status  VARCHAR(20)    NOT NULL,
    message       NVARCHAR(500)  NULL,
    configured    BIT            NOT NULL CONSTRAINT df_doc_field_configured DEFAULT 0,
    created_at    DATETIME2      NOT NULL CONSTRAINT df_doc_field_created DEFAULT SYSDATETIME(),
    value_key     AS CAST(LEFT(field_value, 400) AS NVARCHAR(400)) PERSISTED,
    CONSTRAINT uq_doc_field UNIQUE (doc_id, field_name)
) WITH (DATA_COMPRESSION = PAGE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_field_search' AND object_id = OBJECT_ID(N'ocr.doc_field'))
    CREATE INDEX ix_doc_field_search ON ocr.doc_field (field_name, value_key) INCLUDE (doc_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_field_result' AND object_id = OBJECT_ID(N'ocr.doc_field'))
    CREATE INDEX ix_doc_field_result ON ocr.doc_field (result_id);

-- -----------------------------------------------------------------------------
-- doc_field_correction
-- -----------------------------------------------------------------------------
IF OBJECT_ID(N'ocr.doc_field_correction', N'U') IS NULL
CREATE TABLE ocr.doc_field_correction (
    id                BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT pk_doc_field_correction PRIMARY KEY,
    doc_id            BIGINT         NOT NULL CONSTRAINT fk_doc_field_correction_job REFERENCES ocr.doc_job (id),
    field_name        NVARCHAR(200)  NOT NULL,
    original_value    NVARCHAR(4000) NULL,
    corrected_value   NVARCHAR(4000) NULL,
    reason            VARCHAR(30)    NOT NULL,
    comment_text      NVARCHAR(1000) NULL,
    corrected_by      NVARCHAR(100)  NOT NULL,
    corrected_at      DATETIME2      NOT NULL CONSTRAINT df_doc_field_correction_at DEFAULT SYSDATETIME(),
    active            BIT            NOT NULL CONSTRAINT df_doc_field_correction_active DEFAULT 1,
    used_for_training BIT            NOT NULL CONSTRAINT df_doc_field_correction_training DEFAULT 0
);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_field_correction' AND object_id = OBJECT_ID(N'ocr.doc_field_correction'))
    CREATE INDEX ix_doc_field_correction ON ocr.doc_field_correction (doc_id, field_name, active);

-- -----------------------------------------------------------------------------
-- doc_status_history
-- -----------------------------------------------------------------------------
IF OBJECT_ID(N'ocr.doc_status_history', N'U') IS NULL
CREATE TABLE ocr.doc_status_history (
    id           BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT pk_doc_status_history PRIMARY KEY,
    doc_id       BIGINT         NOT NULL CONSTRAINT fk_doc_status_history_job REFERENCES ocr.doc_job (id),
    from_status  VARCHAR(20)    NULL,
    to_status    VARCHAR(20)    NOT NULL,
    stage        VARCHAR(20)    NOT NULL,
    note         NVARCHAR(2000) NULL,
    changed_by   NVARCHAR(100)  NOT NULL CONSTRAINT df_doc_status_history_by DEFAULT 'batch',
    changed_at   DATETIME2      NOT NULL CONSTRAINT df_doc_status_history_at DEFAULT SYSDATETIME()
) WITH (DATA_COMPRESSION = PAGE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_status_history_doc' AND object_id = OBJECT_ID(N'ocr.doc_status_history'))
    CREATE INDEX ix_doc_status_history_doc ON ocr.doc_status_history (doc_id, id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_status_history_at' AND object_id = OBJECT_ID(N'ocr.doc_status_history'))
    CREATE INDEX ix_doc_status_history_at ON ocr.doc_status_history (changed_at);

-- -----------------------------------------------------------------------------
-- doc_error
-- -----------------------------------------------------------------------------
IF OBJECT_ID(N'ocr.doc_error', N'U') IS NULL
CREATE TABLE ocr.doc_error (
    id            BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT pk_doc_error PRIMARY KEY,
    doc_id        BIGINT         NOT NULL CONSTRAINT fk_doc_error_job REFERENCES ocr.doc_job (id),
    stage         VARCHAR(20)    NOT NULL,
    attempt_no    INT            NOT NULL,
    error_class   NVARCHAR(200)  NULL,
    error_message NVARCHAR(2000) NULL,
    http_status   INT            NULL,
    retryable     BIT            NOT NULL,
    created_at    DATETIME2      NOT NULL CONSTRAINT df_doc_error_created DEFAULT SYSDATETIME()
) WITH (DATA_COMPRESSION = PAGE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_error_doc' AND object_id = OBJECT_ID(N'ocr.doc_error'))
    CREATE INDEX ix_doc_error_doc ON ocr.doc_error (doc_id, id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_error_at' AND object_id = OBJECT_ID(N'ocr.doc_error'))
    CREATE INDEX ix_doc_error_at ON ocr.doc_error (created_at);

-- -----------------------------------------------------------------------------
-- doc_reprocess_request
-- -----------------------------------------------------------------------------
IF OBJECT_ID(N'ocr.doc_reprocess_request', N'U') IS NULL
CREATE TABLE ocr.doc_reprocess_request (
    id              BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT pk_doc_reprocess_request PRIMARY KEY,
    from_stage      VARCHAR(20)    NOT NULL,
    doc_id          BIGINT         NULL CONSTRAINT fk_doc_reprocess_request_job REFERENCES ocr.doc_job (id),
    doc_type        VARCHAR(50)    NULL,
    current_status  VARCHAR(20)    NULL,
    failed_stage    VARCHAR(20)    NULL,
    reason          NVARCHAR(1000) NULL,
    requested_by    NVARCHAR(100)  NOT NULL,
    requested_at    DATETIME2      NOT NULL CONSTRAINT df_doc_reprocess_request_at DEFAULT SYSDATETIME(),
    state           VARCHAR(20)    NOT NULL CONSTRAINT df_doc_reprocess_request_state DEFAULT 'PENDING',
    applied_count   INT            NULL,
    applied_at      DATETIME2      NULL,
    message         NVARCHAR(1000) NULL,
    CONSTRAINT ck_reprocess_stage CHECK (from_stage IN ('CLASSIFY', 'EXTRACT', 'MAP')),
    CONSTRAINT ck_reprocess_state CHECK (state IN ('PENDING', 'APPLIED', 'REJECTED'))
);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_reprocess_state' AND object_id = OBJECT_ID(N'ocr.doc_reprocess_request'))
    CREATE INDEX ix_doc_reprocess_state ON ocr.doc_reprocess_request (state, id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'ix_doc_reprocess_doc' AND object_id = OBJECT_ID(N'ocr.doc_reprocess_request'))
    CREATE INDEX ix_doc_reprocess_doc ON ocr.doc_reprocess_request (doc_id);

-- -----------------------------------------------------------------------------
-- v_doc_field_final: the value downstream systems should use (correction wins)
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW ocr.v_doc_field_final AS
SELECT f.doc_id,
       f.doc_type,
       f.field_name,
       COALESCE(c.corrected_value, f.field_value)              AS final_value,
       CASE WHEN c.id IS NULL THEN 'MODEL' ELSE 'CORRECTED' END AS value_source,
       f.confidence,
       f.field_status,
       f.configured
FROM ocr.doc_field f
LEFT JOIN ocr.doc_field_correction c
       ON c.doc_id = f.doc_id AND c.field_name = f.field_name AND c.active = 1;
