-- =============================================================================
-- Vision OCR - application schema for H2 (local / demo)
-- Production (SQL Server) uses schema-app-sqlserver.sql - keep both in sync.
-- Idempotent (IF NOT EXISTS).
--
--   doc_job                 one row per input file = current state (the "work queue")
--   doc_azure_result        every successful Azure call: full JSON + simplified fields (history kept)
--   doc_field               extracted fields of the latest mapping, one row per field (any doc type)
--   doc_field_correction    human corrections (never overwrite model output)
--   doc_status_history      every status transition (audit trail)
--   doc_error               every failure, with stage / attempt / retryable flag
--   doc_reprocess_request   operator requests to re-run documents from a given stage
--   v_doc_field_final       what downstream systems read: correction wins over extraction
--
-- Field structure is generic: doc_field has one row per field, so a new doc type with
-- different fields needs no schema change. doc_job.extracted_json holds the same values as
-- one JSON object per document.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- doc_job: current state of each document
--   status: NEW -> CLASSIFIED -> EXTRACTED -> COMPLETED
--                                          \-> REVIEW   (human needed)
--           ERROR  = failed, will be retried automatically at next_retry_at
--           FAILED = non-retryable or retries exhausted; needs a reprocess request
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS doc_job (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path           VARCHAR(1024) NOT NULL,
    file_name           VARCHAR(255)  NOT NULL,
    file_hash           VARCHAR(64)   NOT NULL,          -- SHA-256, dedupe key
    file_size           BIGINT,
    status              VARCHAR(20)   NOT NULL,
    doc_type            VARCHAR(50),
    classifier_label    VARCHAR(100),
    classify_confidence DOUBLE PRECISION,
    pages               VARCHAR(100),                    -- page range to extract, e.g. "1-2"
    model_id            VARCHAR(200),                    -- extraction model last used
    doc_confidence      DOUBLE PRECISION,
    review_reasons      VARCHAR(2000),                   -- reason codes, semicolon separated
    extracted_json      CLOB,                            -- {"fieldName": "value", ...} of the latest mapping
    failed_stage        VARCHAR(20),                     -- INGEST | CLASSIFY | EXTRACT | MAP
    retry_count         INT DEFAULT 0 NOT NULL,          -- consecutive failures of failed_stage
    next_retry_at       TIMESTAMP,                       -- when an ERROR row is retried
    last_error          VARCHAR(2000),
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_doc_job_hash UNIQUE (file_hash),
    CONSTRAINT ck_doc_job_status CHECK (status IN
        ('NEW', 'CLASSIFIED', 'EXTRACTED', 'COMPLETED', 'REVIEW', 'ERROR', 'FAILED'))
);
CREATE INDEX IF NOT EXISTS ix_doc_job_status ON doc_job (status, id);
CREATE INDEX IF NOT EXISTS ix_doc_job_retry  ON doc_job (status, next_retry_at);
CREATE INDEX IF NOT EXISTS ix_doc_job_type   ON doc_job (doc_type, status, created_at);

-- -----------------------------------------------------------------------------
-- doc_azure_result: every successful Azure response, never overwritten.
--   Re-running the MAP stage reads fields_json from the current row, so mapping
--   rules can change and be re-applied without paying for Azure again.
--   Comparing rows of different model_id shows what a new model version changed.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS doc_azure_result (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id          BIGINT       NOT NULL REFERENCES doc_job (id),
    operation       VARCHAR(20)  NOT NULL,               -- CLASSIFY | EXTRACT
    model_id        VARCHAR(200) NOT NULL,               -- classifier id or extraction model id
    api_version     VARCHAR(20),
    doc_confidence  DOUBLE PRECISION,
    result_json     CLOB,                                -- full Azure AnalyzeResult
    fields_json     CLOB,                                -- simplified fields (name, value, confidence), EXTRACT only
    duration_ms     BIGINT,
    is_current      BOOLEAN DEFAULT TRUE NOT NULL,       -- latest result per (doc_id, operation)
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_doc_azure_result_op CHECK (operation IN ('CLASSIFY', 'EXTRACT'))
);
CREATE INDEX IF NOT EXISTS ix_doc_azure_result_doc ON doc_azure_result (doc_id, operation, is_current);

-- -----------------------------------------------------------------------------
-- doc_field: extracted fields from the latest MAP run (replaced on every re-map).
--   Generic key/value rows: every field the Azure model returns is stored, whether or not
--   it is declared in the doc type XML (configured = TRUE when XML rules were applied).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS doc_field (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id        BIGINT        NOT NULL REFERENCES doc_job (id),
    result_id     BIGINT        REFERENCES doc_azure_result (id),   -- which Azure result it came from
    doc_type      VARCHAR(50)   NOT NULL,
    field_name    VARCHAR(200)  NOT NULL,   -- canonical name (XML) or the Azure field name
    azure_field   VARCHAR(200),             -- field name as returned by the Azure model
    field_value   VARCHAR(4000),
    raw_value     VARCHAR(4000),            -- value before normalization
    confidence    DOUBLE PRECISION,
    field_status  VARCHAR(20)   NOT NULL,   -- OK | MISSING | LOW_CONFIDENCE | INVALID
    message       VARCHAR(500),
    configured    BOOLEAN DEFAULT FALSE NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    value_key     VARCHAR(400) GENERATED ALWAYS AS (LEFT(field_value, 400)),  -- indexed search key
    CONSTRAINT uq_doc_field UNIQUE (doc_id, field_name)
);
CREATE INDEX IF NOT EXISTS ix_doc_field_search ON doc_field (field_name, value_key);

-- -----------------------------------------------------------------------------
-- doc_field_correction: reviewer fixes. Keyed by field name (not doc_field.id) so
-- corrections survive re-mapping/re-extraction. Only one active row per field.
-- Also the source of new training labels.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS doc_field_correction (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id          BIGINT        NOT NULL REFERENCES doc_job (id),
    field_name      VARCHAR(100)  NOT NULL,
    original_value  VARCHAR(4000),        -- value at correction time
    corrected_value VARCHAR(4000),
    reason          VARCHAR(30)   NOT NULL, -- OCR_MISREAD | WRONG_REGION | MISSING | OTHER
    comment_text    VARCHAR(1000),
    corrected_by    VARCHAR(100)  NOT NULL,
    corrected_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active          BOOLEAN DEFAULT TRUE NOT NULL,
    used_for_training BOOLEAN DEFAULT FALSE NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_doc_field_correction ON doc_field_correction (doc_id, field_name, active);

-- -----------------------------------------------------------------------------
-- doc_status_history: append-only audit of every transition
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS doc_status_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id       BIGINT       NOT NULL REFERENCES doc_job (id),
    from_status  VARCHAR(20),
    to_status    VARCHAR(20)  NOT NULL,
    stage        VARCHAR(20)  NOT NULL,   -- INGEST | CLASSIFY | EXTRACT | MAP | RETRY | REPROCESS | REVIEW
    note         VARCHAR(2000),
    changed_by   VARCHAR(100) DEFAULT 'batch' NOT NULL,
    changed_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_doc_status_history_doc ON doc_status_history (doc_id, id);

-- -----------------------------------------------------------------------------
-- doc_error: every failure (a document can fail several times before succeeding)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS doc_error (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id        BIGINT        NOT NULL REFERENCES doc_job (id),
    stage         VARCHAR(20)   NOT NULL,
    attempt_no    INT           NOT NULL,
    error_class   VARCHAR(200),
    error_message VARCHAR(2000),
    http_status   INT,
    retryable     BOOLEAN       NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_doc_error_doc ON doc_error (doc_id, id);

-- -----------------------------------------------------------------------------
-- doc_reprocess_request: operators insert a row, the next job run applies it.
--   from_stage CLASSIFY -> back to NEW        (re-classify + re-extract + re-map)
--              EXTRACT  -> back to CLASSIFIED (re-extract with current model + re-map)
--              MAP      -> back to EXTRACTED  (re-map only, no Azure cost)
--   Target: a single doc_id, or any combination of doc_type / current_status /
--   failed_stage filters (at least one is required).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS doc_reprocess_request (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_stage      VARCHAR(20)  NOT NULL,
    doc_id          BIGINT       REFERENCES doc_job (id),
    doc_type        VARCHAR(50),
    current_status  VARCHAR(20),
    failed_stage    VARCHAR(20),
    reason          VARCHAR(1000),
    requested_by    VARCHAR(100) NOT NULL,
    requested_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    state           VARCHAR(20)  DEFAULT 'PENDING' NOT NULL,   -- PENDING | APPLIED | REJECTED
    applied_count   INT,
    applied_at      TIMESTAMP,
    message         VARCHAR(1000),
    CONSTRAINT ck_reprocess_stage CHECK (from_stage IN ('CLASSIFY', 'EXTRACT', 'MAP')),
    CONSTRAINT ck_reprocess_state CHECK (state IN ('PENDING', 'APPLIED', 'REJECTED'))
);
CREATE INDEX IF NOT EXISTS ix_doc_reprocess_state ON doc_reprocess_request (state, id);

-- -----------------------------------------------------------------------------
-- v_doc_field_final: the value downstream systems should use.
-- A human correction always wins over the model output.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_doc_field_final AS
SELECT f.doc_id,
       f.doc_type,
       f.field_name,
       COALESCE(c.corrected_value, f.field_value)              AS final_value,
       CASE WHEN c.id IS NULL THEN 'MODEL' ELSE 'CORRECTED' END AS value_source,
       f.confidence,
       f.field_status,
       f.configured
FROM doc_field f
LEFT JOIN doc_field_correction c
       ON c.doc_id = f.doc_id AND c.field_name = f.field_name AND c.active = TRUE;
