-- =============================================================================
-- Vision OCR - operator cookbook for SQL Server (SSMS / Azure Data Studio)
-- All objects of the job are in schema ocr.
-- Changes are picked up by the NEXT job run (recoveryStep runs first).
-- =============================================================================
DECLARE @doc_id BIGINT = 1;

-- ---------------------------------------------------------------- monitoring

-- Queue overview
SELECT COALESCE(doc_type, '-') AS doc_type, status, COUNT(*) AS docs
FROM ocr.doc_job GROUP BY doc_type, status ORDER BY doc_type, status;

-- Documents waiting for an automatic retry, and when
SELECT id, file_name, failed_stage, retry_count, next_retry_at, last_error
FROM ocr.doc_job WHERE status = 'ERROR' ORDER BY next_retry_at;

-- Documents that need an operator (not retried automatically)
SELECT id, file_name, failed_stage, retry_count, last_error, updated_at
FROM ocr.doc_job WHERE status = 'FAILED' ORDER BY updated_at DESC;

-- Most common errors in the last 24h (spot an outage or a bad model/config)
SELECT stage, error_class, http_status, retryable, COUNT(*) AS n, MAX(created_at) AS last_seen
FROM ocr.doc_error WHERE created_at > DATEADD(DAY, -1, SYSDATETIME())
GROUP BY stage, error_class, http_status, retryable ORDER BY n DESC;

-- Review queue with reasons
SELECT id, file_name, doc_type, review_reasons, updated_at
FROM ocr.doc_job WHERE status = 'REVIEW' ORDER BY updated_at;

-- Full timeline of one document
SELECT changed_at, stage, from_status, to_status, changed_by, note
FROM ocr.doc_status_history WHERE doc_id = @doc_id ORDER BY id;

-- Full Azure response of one document (stored GZIP-compressed; result_json holds rows from older versions)
SELECT id, operation, model_id, created_at,
       COALESCE(CAST(DECOMPRESS(result_json_gz) AS NVARCHAR(MAX)), result_json) AS azure_json
FROM ocr.doc_azure_result WHERE doc_id = @doc_id AND is_current = 1;

-- All Azure calls for one document (model versions, timings)
SELECT id, operation, model_id, doc_confidence, duration_ms, is_current, created_at
FROM ocr.doc_azure_result WHERE doc_id = @doc_id ORDER BY id;

-- ---------------------------------------------------------------- extracted data

-- One document: all values as JSON, and as rows (corrections applied)
SELECT extracted_json FROM ocr.doc_job WHERE id = @doc_id;
SELECT field_name, final_value, value_source, confidence, field_status
FROM ocr.v_doc_field_final WHERE doc_id = @doc_id ORDER BY field_name;

-- Flat view per doc type (generated by the job): one row per document, one column per field
SELECT * FROM ocr.v_doc_auto_pay_auth ORDER BY doc_id;

-- Find documents by a field value (uses index ix_doc_field_search)
SELECT j.id, j.file_name, j.status
FROM ocr.doc_field f JOIN ocr.doc_job j ON j.id = f.doc_id
WHERE f.field_name = 'lenderAccountNumber' AND f.value_key = N'LN-4455667';

-- Read JSON directly (SQL Server)
SELECT id, file_name, JSON_VALUE(extracted_json, '$.routingNumber') AS routing_number
FROM ocr.doc_job WHERE doc_type = 'AUTO_PAY_AUTH' AND status = 'COMPLETED';

SELECT j.id, kv.[key] AS field_name, kv.[value] AS field_value
FROM ocr.doc_job j CROSS APPLY OPENJSON(j.extracted_json) kv
WHERE j.id = @doc_id;

-- ---------------------------------------------------------------- reprocessing
-- from_stage: CLASSIFY (re-classify + extract + map) | EXTRACT (re-extract + map) | MAP (re-map only, no Azure cost)

-- One document, e.g. after fixing a mapping rule
INSERT INTO ocr.doc_reprocess_request (from_stage, doc_id, reason, requested_by)
VALUES ('MAP', @doc_id, 'routing rule fixed', 'jdoe');

-- All FAILED extractions (e.g. Azure key was wrong / model id was missing, now fixed)
INSERT INTO ocr.doc_reprocess_request (from_stage, current_status, failed_stage, reason, requested_by)
VALUES ('EXTRACT', 'FAILED', 'EXTRACT', 'model id fixed in config', 'jdoe');

-- Re-extract everything of a doc type with a new model version (set the new model id first!)
INSERT INTO ocr.doc_reprocess_request (from_stage, doc_type, current_status, reason, requested_by)
VALUES ('EXTRACT', 'AUTO_PAY_AUTH', 'REVIEW', 'autopay-neural-v3 deployed', 'jdoe');

-- Re-apply mapping/validation rules to all completed docs of a type (free - uses stored Azure JSON)
INSERT INTO ocr.doc_reprocess_request (from_stage, doc_type, current_status, reason, requested_by)
VALUES ('MAP', 'AUTO_PAY_AUTH', 'COMPLETED', 'new validation rule', 'jdoe');

-- Retry ERROR documents now instead of waiting for next_retry_at
UPDATE ocr.doc_job SET next_retry_at = SYSDATETIME() WHERE status = 'ERROR';

-- Result of the requests
SELECT TOP 50 id, from_stage, doc_id, doc_type, current_status, state, applied_count, message, applied_at
FROM ocr.doc_reprocess_request ORDER BY id DESC;

-- ---------------------------------------------------------------- review / corrections
-- (a review UI should do this in one transaction)

-- Correct a field
UPDATE ocr.doc_field_correction SET active = 0 WHERE doc_id = @doc_id AND field_name = 'customerName' AND active = 1;
INSERT INTO ocr.doc_field_correction (doc_id, field_name, original_value, corrected_value, reason, corrected_by)
SELECT doc_id, field_name, field_value, N'JOHN Q SAMPLE', 'OCR_MISREAD', 'reviewer1'
FROM ocr.doc_field WHERE doc_id = @doc_id AND field_name = 'customerName';

-- Approve the document after review
INSERT INTO ocr.doc_status_history (doc_id, from_status, to_status, stage, note, changed_by)
SELECT id, status, 'COMPLETED', 'REVIEW', 'approved after correction', 'reviewer1' FROM ocr.doc_job WHERE id = @doc_id AND status = 'REVIEW';
UPDATE ocr.doc_job SET status = 'COMPLETED', updated_at = SYSDATETIME() WHERE id = @doc_id AND status = 'REVIEW';

-- Correction rate per field (tells you what to retrain)
SELECT j.doc_type, c.field_name, c.reason, COUNT(*) AS corrections
FROM ocr.doc_field_correction c JOIN ocr.doc_job j ON j.id = c.doc_id
WHERE c.active = 1 GROUP BY j.doc_type, c.field_name, c.reason ORDER BY corrections DESC;

-- ---------------------------------------------------------------- housekeeping
-- The job's housekeepingStep applies the retention.* settings automatically on every run
-- (old full Azure JSON, history/error rows, Spring Batch run records). Manual equivalents below.

-- Row counts and sizes of the job's tables
SELECT t.name AS table_name, SUM(p.rows) AS row_count,
       CAST(SUM(a.total_pages) * 8 / 1024.0 AS DECIMAL(12,1)) AS size_mb
FROM sys.tables t
JOIN sys.schemas s ON s.schema_id = t.schema_id
JOIN sys.partitions p ON p.object_id = t.object_id AND p.index_id IN (0, 1)
JOIN sys.allocation_units a ON a.container_id = p.partition_id
WHERE s.name = 'ocr'
GROUP BY t.name ORDER BY size_mb DESC;

-- One-time (DBA, off-hours): PAGE-compress tables created by an earlier version of the script.
-- New installations get this automatically.
ALTER TABLE ocr.doc_field          REBUILD WITH (DATA_COMPRESSION = PAGE);
ALTER TABLE ocr.doc_status_history REBUILD WITH (DATA_COMPRESSION = PAGE);
ALTER TABLE ocr.doc_error          REBUILD WITH (DATA_COMPRESSION = PAGE);
ALTER TABLE ocr.doc_azure_result   REBUILD WITH (DATA_COMPRESSION = PAGE);

-- Optional: fast search on a JSON key you query often (repeat per key)
-- ALTER TABLE ocr.doc_job ADD lender_account AS CAST(JSON_VALUE(extracted_json, '$.lenderAccountNumber') AS NVARCHAR(100));
-- CREATE INDEX ix_doc_job_lender_account ON ocr.doc_job (lender_account);

-- Clear the full Azure JSON of old results by hand (keep fields_json for re-mapping)
UPDATE TOP (5000) ocr.doc_azure_result SET result_json_gz = NULL, result_json = NULL
WHERE created_at < DATEADD(DAY, -180, SYSDATETIME()) AND (result_json_gz IS NOT NULL OR result_json IS NOT NULL);
